export const WEAPONS = [
  {
    rarity: 6,
    name: "遺忘",
    category: "アーツユニット",
    base: "知性UP",
    additional: "アーツダメージUP",
    skill: "夜幕",
  },
  {
    rarity: 6,
    name: "騎士精神",
    category: "アーツユニット",
    base: "意志UP",
    additional: "HPアップ",
    skill: "治療",
  },
  {
    rarity: 6,
    name: "作品：蝕跡",
    category: "アーツユニット",
    base: "意志UP",
    additional: "自然ダメージUP",
    skill: "圧制",
  },
  {
    rarity: 6,
    name: "使命必達",
    category: "アーツユニット",
    base: "意志UP",
    additional: "必殺技効率UP",
    skill: "追襲",
  },
  {
    rarity: 6,
    name: "蒼星の囁き",
    category: "アーツユニット",
    base: "知性UP",
    additional: "回復効率UP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "破壊ユニット",
    category: "アーツユニット",
    base: "メイン能力UP",
    additional: "アーツ強度UP",
    skill: "噴発",
  },
  {
    rarity: 6,
    name: "ナビゲーター",
    category: "拳銃",
    base: "知性UP",
    additional: "寒冷ダメージUP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "芸術の独裁者",
    category: "拳銃",
    base: "知性UP",
    additional: "会心率UP",
    skill: "切骨",
  },
  {
    rarity: 6,
    name: "同類共食",
    category: "拳銃",
    base: "メイン能力UP",
    additional: "アーツダメージUP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "楔",
    category: "拳銃",
    base: "メイン能力UP",
    additional: "会心率UP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "クラヴェンガー",
    category: "大剣",
    base: "筋力UP",
    additional: "攻撃力UP",
    skill: "噴発",
  },
  {
    rarity: 6,
    name: "鑑",
    category: "大剣",
    base: "メイン能力UP",
    additional: "攻撃力UP",
    skill: "圧制",
  },
  {
    rarity: 6,
    name: "昔日の逸品",
    category: "大剣",
    base: "意志UP",
    additional: "HPアップ",
    skill: "効率",
  },
  {
    rarity: 6,
    name: "大雷斑",
    category: "大剣",
    base: "筋力UP",
    additional: "HPアップ",
    skill: "治癒",
  },
  {
    rarity: 6,
    name: "破砕君主",
    category: "大剣",
    base: "筋力UP",
    additional: "会心率UP",
    skill: "破砕",
  },
  {
    rarity: 6,
    name: "J.E.T.",
    category: "長柄武器",
    base: "メイン能力UP",
    additional: "攻撃力UP",
    skill: "圧制",
  },
  {
    rarity: 6,
    name: "負山",
    category: "長柄武器",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "効率",
  },
  {
    rarity: 6,
    name: "勇猛",
    category: "長柄武器",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "巧技",
  },
  {
    rarity: 6,
    name: "ダークトーチ",
    category: "片手剣",
    base: "知性UP",
    additional: "灼熱ダメージUP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "テルミット・カッター",
    category: "片手剣",
    base: "意志UP",
    additional: "攻撃力UP",
    skill: "流回",
  },
  {
    rarity: 6,
    name: "フーヤオ",
    category: "片手剣",
    base: "メイン能力UP",
    additional: "会心率UP",
    skill: "夜幕",
  },
  {
    rarity: 6,
    name: "フレイムフォージ",
    category: "片手剣",
    base: "知性UP",
    additional: "攻撃力UP",
    skill: "夜幕",
  },
  {
    rarity: 6,
    name: "輝かしき名声",
    category: "片手剣",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "残虐",
  },
  {
    rarity: 6,
    name: "大願",
    category: "片手剣",
    base: "敏捷UP",
    additional: "攻撃力UP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "白夜新星",
    category: "片手剣",
    base: "メイン能力UP",
    additional: "アーツ強度UP",
    skill: "付術",
  },
  {
    rarity: 6,
    name: "不知帰",
    category: "片手剣",
    base: "意志UP",
    additional: "攻撃力UP",
    skill: "流回",
  },
  {
    rarity: 5,
    name: "O.B.J.術識",
    category: "アーツユニット",
    base: "知性UP",
    additional: "アーツ強度UP",
    skill: "追襲",
  },
  {
    rarity: 5,
    name: "荒野迷走",
    category: "アーツユニット",
    base: "知性UP",
    additional: "電磁ダメージUP",
    skill: "付術",
  },
  {
    rarity: 5,
    name: "術無",
    category: "アーツユニット",
    base: "意志UP",
    additional: "必殺技効率UP",
    skill: "昂揚",
  },
  {
    rarity: 5,
    name: "弔いの詩",
    category: "アーツユニット",
    base: "知性UP",
    additional: "攻撃力UP",
    skill: "夜幕",
  },
  {
    rarity: 5,
    name: "布教の自由",
    category: "アーツユニット",
    base: "意志UP",
    additional: "回復効率UP",
    skill: "治癒",
  },
  {
    rarity: 5,
    name: "O.B.J.迅速",
    category: "拳銃",
    base: "敏捷UP",
    additional: "必殺技効率UP",
    skill: "噴発",
  },
  {
    rarity: 5,
    name: "合理的決別",
    category: "拳銃",
    base: "筋力UP",
    additional: "灼熱ダメージUP",
    skill: "追襲",
  },
  {
    rarity: 5,
    name: "作品：衆生",
    category: "拳銃",
    base: "敏捷UP",
    additional: "アーツダメージUP",
    skill: "付術",
  },
  {
    rarity: 5,
    name: "O.B.J.重責",
    category: "大剣",
    base: "筋力UP",
    additional: "HPアップ",
    skill: "効率",
  },
  {
    rarity: 5,
    name: "最期の声",
    category: "大剣",
    base: "筋力UP",
    additional: "HPアップ",
    skill: "治癒",
  },
  {
    rarity: 5,
    name: "千古恒常",
    category: "大剣",
    base: "筋力UP",
    additional: "アーツ強度UP",
    skill: "残虐",
  },
  {
    rarity: 5,
    name: "探龍",
    category: "大剣",
    base: "筋力UP",
    additional: "必殺技効率UP",
    skill: "噴発",
  },
  {
    rarity: 5,
    name: "O.B.J.鋭矛",
    category: "長柄武器",
    base: "意志UP",
    additional: "物理ダメージUP",
    skill: "付術",
  },
  {
    rarity: 5,
    name: "求心の槍",
    category: "長柄武器",
    base: "意志UP",
    additional: "電磁ダメージUP",
    skill: "圧制",
  },
  {
    rarity: 5,
    name: "正義嵌合",
    category: "長柄武器",
    base: "筋力UP",
    additional: "必殺技効率UP",
    skill: "残虐",
  },
  {
    rarity: 5,
    name: "O.B.J.軽刃",
    category: "片手剣",
    base: "敏捷UP",
    additional: "攻撃力UP",
    skill: "流回",
  },
  {
    rarity: 5,
    name: "フィンチェイサー3.0",
    category: "片手剣",
    base: "筋力UP",
    additional: "寒冷ダメージUP",
    skill: "圧制",
  },
  {
    rarity: 5,
    name: "仰止",
    category: "片手剣",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "夜幕",
  },
  {
    rarity: 5,
    name: "堅城鋳造者",
    category: "片手剣",
    base: "知性UP",
    additional: "必殺技効率UP",
    skill: "昂揚",
  },
  {
    rarity: 5,
    name: "鋼鉄余音",
    category: "片手剣",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "巧技",
  },
  {
    rarity: 5,
    name: "十二問",
    category: "片手剣",
    base: "敏捷UP",
    additional: "攻撃力UP",
    skill: "付術",
  },
  {
    rarity: 4,
    name: "オート・ハイパーノヴァ",
    category: "アーツユニット",
    base: "知性UP",
    additional: "アーツダメージUP",
    skill: "昂揚",
  },
  {
    rarity: 4,
    name: "蛍光雷羽",
    category: "アーツユニット",
    base: "意志UP",
    additional: "攻撃力UP",
    skill: "制圧",
  },
  {
    rarity: 4,
    name: "ロアーガード",
    category: "拳銃",
    base: "知性UP",
    additional: "攻撃力UP",
    skill: "制圧",
  },
  {
    rarity: 4,
    name: "長路",
    category: "拳銃",
    base: "筋力UP",
    additional: "アーツダメージUP",
    skill: "追襲",
  },
  {
    rarity: 4,
    name: "工業零点一",
    category: "大剣",
    base: "筋力UP",
    additional: "攻撃力UP",
    skill: "制圧",
  },
  {
    rarity: 4,
    name: "鍛冶師",
    category: "大剣",
    base: "意志UP",
    additional: "HPアップ",
    skill: "破砕",
  },
  {
    rarity: 4,
    name: "アンゲロス・スレイヤー",
    category: "長柄武器",
    base: "意志UP",
    additional: "アーツダメージUP",
    skill: "制圧",
  },
  {
    rarity: 4,
    name: "開拓者の道標",
    category: "長柄武器",
    base: "敏捷UP",
    additional: "攻撃力UP",
    skill: "昂揚",
  },
  {
    rarity: 4,
    name: "緊急設計",
    category: "片手剣",
    base: "敏捷UP",
    additional: "物理ダメージUP",
    skill: "制圧",
  },
  {
    rarity: 4,
    name: "潮流",
    category: "片手剣",
    base: "知性UP",
    additional: "攻撃力UP",
    skill: "追襲",
  },
];
